"""
SQLAlchemy models for MySQL database
"""
from datetime import datetime
from sqlalchemy import Column, Integer, String, Float, DateTime, Boolean, Text, ForeignKey, Enum, JSON
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import relationship
import enum

Base = declarative_base()


class UserRole(str, enum.Enum):
    """User roles for RBAC"""
    ADMIN = "admin"
    OPERATOR = "operator"
    VIEWER = "viewer"


class ActionStatus(str, enum.Enum):
    """Status of automated actions"""
    PENDING = "pending"
    IN_PROGRESS = "in_progress"
    SUCCESS = "success"
    FAILED = "failed"
    SKIPPED = "skipped"


class AlertSeverity(str, enum.Enum):
    """Alert severity levels"""
    INFO = "info"
    WARNING = "warning"
    CRITICAL = "critical"


class User(Base):
    """User accounts with RBAC"""
    __tablename__ = "users"
    
    id = Column(Integer, primary_key=True, index=True)
    username = Column(String(50), unique=True, nullable=False, index=True)
    email = Column(String(100), unique=True, nullable=False)
    hashed_password = Column(String(255), nullable=False)
    role = Column(Enum(UserRole), default=UserRole.VIEWER, nullable=False)
    is_active = Column(Boolean, default=True)
    created_at = Column(DateTime, default=datetime.utcnow)
    last_login = Column(DateTime, nullable=True)
    
    # Relationships
    audit_logs = relationship("AuditLog", back_populates="user")


class Node(Base):
    """VPS nodes (master and slaves)"""
    __tablename__ = "nodes"
    
    id = Column(Integer, primary_key=True, index=True)
    name = Column(String(100), nullable=False)
    ip_address = Column(String(45), unique=True, nullable=False, index=True)
    node_type = Column(String(20), default="slave")  # master or slave
    is_active = Column(Boolean, default=True)
    last_heartbeat = Column(DateTime, nullable=True)
    agent_version = Column(String(20), nullable=True)
    os_type = Column(String(50), nullable=True)
    os_version = Column(String(50), nullable=True)
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
    
    # Relationships
    containers = relationship("Container", back_populates="node")
    actions = relationship("Action", back_populates="node")
    alerts = relationship("Alert", back_populates="node")


class Container(Base):
    """Docker containers tracked per node"""
    __tablename__ = "containers"
    
    id = Column(Integer, primary_key=True, index=True)
    node_id = Column(Integer, ForeignKey("nodes.id"), nullable=False)
    container_id = Column(String(64), nullable=False, index=True)
    name = Column(String(255), nullable=False)
    image = Column(String(255), nullable=False)
    status = Column(String(50), nullable=False)  # running, stopped, etc.
    ports = Column(JSON, nullable=True)  # Port mappings
    first_deployed = Column(DateTime, nullable=True)
    last_updated = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
    is_monitored = Column(Boolean, default=True)
    
    # Relationships
    node = relationship("Node", back_populates="containers")
    actions = relationship("Action", back_populates="container")


class Action(Base):
    """Automated actions performed by agents"""
    __tablename__ = "actions"
    
    id = Column(Integer, primary_key=True, index=True)
    node_id = Column(Integer, ForeignKey("nodes.id"), nullable=False)
    container_id = Column(Integer, ForeignKey("containers.id"), nullable=True)
    action_type = Column(String(50), nullable=False)  # restart, cleanup, cache_clear, etc.
    status = Column(Enum(ActionStatus), default=ActionStatus.PENDING, nullable=False)
    reason = Column(Text, nullable=True)
    agent_explanation = Column(Text, nullable=True)  # AI explanation
    triggered_by = Column(String(100), nullable=True)  # anomaly, threshold, manual
    execution_time = Column(Float, nullable=True)  # seconds
    error_message = Column(Text, nullable=True)
    created_at = Column(DateTime, default=datetime.utcnow)
    started_at = Column(DateTime, nullable=True)
    completed_at = Column(DateTime, nullable=True)
    
    # Relationships
    node = relationship("Node", back_populates="actions")
    container = relationship("Container", back_populates="actions")


class Alert(Base):
    """Alerts generated by the system"""
    __tablename__ = "alerts"
    
    id = Column(Integer, primary_key=True, index=True)
    node_id = Column(Integer, ForeignKey("nodes.id"), nullable=False)
    severity = Column(Enum(AlertSeverity), nullable=False)
    title = Column(String(255), nullable=False)
    message = Column(Text, nullable=False)
    metric_type = Column(String(50), nullable=True)  # cpu, memory, disk
    metric_value = Column(Float, nullable=True)
    threshold_value = Column(Float, nullable=True)
    is_resolved = Column(Boolean, default=False)
    resolved_at = Column(DateTime, nullable=True)
    notified_email = Column(Boolean, default=False)
    notified_telegram = Column(Boolean, default=False)
    created_at = Column(DateTime, default=datetime.utcnow, index=True)
    
    # Relationships
    node = relationship("Node", back_populates="alerts")


class AuditLog(Base):
    """Audit logs for compliance (ISO 27001)"""
    __tablename__ = "audit_logs"
    
    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id"), nullable=True)
    action = Column(String(100), nullable=False)
    resource_type = Column(String(50), nullable=True)  # node, container, user
    resource_id = Column(Integer, nullable=True)
    details = Column(JSON, nullable=True)
    ip_address = Column(String(45), nullable=True)
    user_agent = Column(String(255), nullable=True)
    status = Column(String(20), nullable=False)  # success, failed
    created_at = Column(DateTime, default=datetime.utcnow, index=True)
    
    # Relationships
    user = relationship("User", back_populates="audit_logs")


class MLModel(Base):
    """ML model versions and metadata"""
    __tablename__ = "ml_models"
    
    id = Column(Integer, primary_key=True, index=True)
    model_name = Column(String(100), nullable=False)
    version = Column(String(20), nullable=False)
    algorithm = Column(String(50), nullable=False)  # isolation_forest, lstm
    file_path = Column(String(255), nullable=False)
    accuracy = Column(Float, nullable=True)
    training_samples = Column(Integer, nullable=True)
    is_active = Column(Boolean, default=False)
    trained_at = Column(DateTime, default=datetime.utcnow)
    metadata = Column(JSON, nullable=True)
    
    def __repr__(self):
        return f"<MLModel {self.model_name} v{self.version}>"
